{
  imports = [
    ./apps.nix
    ./audio.nix
    ./boot.nix
    ./firefox.nix
    ./gaming.nix
    ./ghostty.nix
    ./git.nix
    ./gnome.nix
    ./helix.nix
    ./ktalk.nix
    ./locale.nix
    ./nemo.nix
    ./networking.nix
    ./nix.nix
    ./state-version.nix
    ./tex.nix
    ./theme.nix
    ./user.nix
    ./virtualisation.nix
    ./vpn.nix
    ./vscode.nix
    ./zsh.nix
  ];
}
